{
 "title": "Pesquisar por Tabela",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Pesquisar",
    "label": "Pesquisar o nome da tabela",
    "query": "SELECT\n  task_id \n FROM task_instance\nWHERE\n   dag_id = 'DataMart' "
   }
  ]
 },
 "panels": [
  {
   "title": "Comparação de execuções",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "rawSql": " SELECT\r\n EXTRACT (EPOCH from MAX(end_date) - MIN(start_date)) AS duration\r\n ,end_date as \"time\"\r\n , task_id as metric\r\n       --EXTRACT(EPOCH FROM (coalesce(ti.end_date, current_timestamp) - ti.start_date ))) as last_duration\r\n    FROM  task_instance\r\n   WHERE  dag_id = 'DataMart'\r\nand  state = 'success'\r\nand  $__timeFilter(execution_date)\r\nand task_id in ($Pesquisar)\r\n--and task_id = 'FT_Operacao'\r\nGROUP BY  end_date, TASK_ID\r\nORDER BY  end_date DESC"
    }
   ]
  },
  {
   "title": "Data e hora de término",
   "type": "singlestat",
   "description": "Horário de término da carga da tabela consultada",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " SELECT task_id || ' -> ' || to_char(end_date,'YYYY-MM-DD HH24:MI:SS')\r\n    FROM  task_instance\r\n   WHERE  dag_id = 'DataMart'\r\n     AND  state = 'success'\r\nand task_id in ($Pesquisar)\r\ngroup by task_id,end_date\r\n"
    }
   ]
  },
  {
   "title": "Horário de execuções por tabela",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": " SELECT  execution_date\r\n      , task_id as metric\r\n       ,  MIN(start_date) AS start\r\n       ,  MAX(end_date) AS end\r\n       ,  MAX(end_date) - MIN(start_date) AS duration\r\n --      ,  AVG(duration)\r\n    FROM  task_instance\r\n   WHERE  dag_id = 'DataMart'\r\n     AND  state = 'success'\r\n     and task_id in ($Pesquisar)\r\nGROUP BY  execution_date, TASK_ID\r\nORDER BY  execution_date DESC\r\n"
    }
   ]
  }
 ]
}